### ISSUE TITLE
Bundle is not Python 3 compatible

### ISSUE THREAD

**Issue by fonnesbeck** [textmate/latex.tmbundle#111]
If a user is running Python 3 as their default, the LaTeX bundle does not work. Most notably, one cannot open the preferences pane. This stems initially from the use of `os.popen4` in `Support/bin/configure.py`, as `popen4` has been replaced by the `subprocess` module in Python 3. Even after changing this, however, one runs into additional compatibility issues in `tmprefs.py`.

**Comment by sanssecours** [comment]
Hi Chris,

commit 948a9976 adds compatibility with Python 3 to the bundle preferences. I will look into fixing the compatibility problems with the remaining scripts sometimes in the future.

Kind regards,
  René

**Comment by sanssecours** [comment]
Hi Chris,

all bundle items now support Python 3. If you encounter any problems please reopen this issue, and comment below.

Kind regards,
  René

**Comment by sorbits** [comment]
@sanssecours While I appreciate the work you have done making the python code compatible with python 3, I think a better fix is to use `/usr/bin/python` in the shebang rather than use `python` from user’s `PATH` (via `/usr/bin/env`).

The reason is that we know what `/usr/bin/python` is and can guarantee the bundle works with that, but we do not know if the user has installed some alternative python, or more likely, have a custom python that lacks pyobjc — the latter is a **very** likely scenario (as it might be implicitly installed by homebrew or MacPorts).

**Comment by sanssecours** [comment]
Hi Allan,

> I think a better fix is to use /usr/bin/python in the shebang rather than use python from user’s PATH (via /usr/bin/env).

you are right, although in my opinion this issue is not about a custom versions of `python`, but rather about the compatibility to the newest version of the language. I don't think using `/usr/bin/python` as shebang is a fix for making the bundle Python 3 compatible :).

The python scripts in commit 2e8d7c93 now always use `/usr/bin/python` as interpreter.

Thanks for the feedback,
  René
