### ISSUE TITLE
citation autocomplete bug

### ISSUE THREAD

**Issue by szymtor** [textmate/latex.tmbundle#115]
Textmate hangs in the following scenario.

I create the following file test.tex:
```latex
\documentclass{article}
\begin{document}
\bibliography{bib}
\end{document}
```
and the following file bib.bib:
```bibtex
@article{A,
author = {A}}
%@article{B}
```
(both files should be saved). Then, in test.tex, I execute: insert citation based on current word.
This hangs Textmate.

**Comment by sanssecours** [comment]
Hi Szymon,

I guess the command is kind of picky when it comes to the structure of a bib file. Fixing this might take some time. 

I would recommend you use the excellent [Bibdesk](http://bibdesk.sourceforge.net) to manage your bibliography entries. If you for example open `bib.bib` in BibDesk and save it, then “BibDesk” will create a file that “Citation Based on Current Word / Selection…” is able to parse correctly.

Kind regards,
  René

**Comment by szymtor** [comment]
Hi René,

thanks for the reply. Actually, I use BibDesk, and you're right – saving this bib files in BibDesk removes the error. The problem is with my coauthors, who submit such bib-files into a common project, and all the sudden this hangs my TextMate (when I try to auto complete a citation). But well, its not a big deal, I just have to beg them not to play such cruel jokes on me...

Best,
Szymon

**Comment by plalteaugal** [comment]
Hi René,

I use Bibdesk with TextMate, but autocompletion does not work in the citation field \cite{xxx}. Of course, I save my bib.bib file whenever I add a bib entry.  Is there anything else I should do? 

Thanks for all of your great work!

Jenny

**Comment by sanssecours** [comment]
Hi Jenny,

theoretically you should only need to press <kbd>⌥⎋</kbd> (Alt-Esc) inside the braces of cite (`\cite{˰}`) and a list with all the entries in the bib file should pop up. You could also enter some characters that are part of the cite key e.g. `~\cite{1986˰}` to narrow down the possible entries. If there is only one fitting entry, then it should be inserted directly.

If the above procedure does not work for you, then it is very likely that the command was not able to parse your bib file. Could you then please post your file so that I can check it and possibly fix your issue.

Kind regards,
  René

---

P.S.: Currently there seems to be a problem if we invoke the completion in an empty “cite” like `\cite{˰}`, since the chosen key also replaces the braces. Instead of `\cite{keyOfBibItem}` we get `\citekeyOfBibItem`. It works correctly if we insert a space in the cite, select it, and then invoke the completion. This might be a bug in TextMate.

@sorbits: Allan, is it intentional that the output of the command replaces the braces, although they are not part of the input? Here is a minimal example to reproduce the behaviour:

1. Create a new bundle item

  ```Ruby
  #!/usr/bin/env ruby18 -wKU
  puts "Hello world"
  ```

  Name: Bla
  Key Equivalent: <kbd>⌥⎋</kbd>
  Input: Selection
  Format: Text
  Output: Replace Input
  Format: Text

2. Create an new file with the following content: `{}`

3. Invoke <kbd>⌥⎋</kbd> inside the braces (`{˰}`)

4. Output: `Hello World`
5. Expected output: `{Hello world}`

**Comment by sorbits** [comment]
@sanssecours Something which isn’t currently exposed in the bundle editor is that commands can have a `fallbackInput` which is used when there is no selection (and input is set to _Selection_).

For the cite completion command the fallback input is _Word_. For empty braces the current word is those braces. This is consistent with what you get if you press <kbd>⌃W</kbd> (Select Word).

So I think the behavior is correct, and the command should special-case getting `{}` as input.

**Comment by sanssecours** [comment]
Hi Allan,

thanks for the quick response.

> So I think the behavior is correct, and the command should special-case getting {} as input

That sounds like a good idea. I will update the command accordingly.

Kind regards,
  René

**Comment by sanssecours** [comment]
Hi,

the newest code should fix the bug reported by Szymon. If anyone has any additional examples that do not work, then please report them. I am always happy about feedback. Even it is about something I broke :).

Thanks,
 René
