### ISSUE TITLE
Tilde sign and spelling

### ISSUE THREAD

**Issue by slavad** [textmate/latex.tmbundle#116]
Hello
Textmate marks words with "~" (non-breaking space) as misspelled when I use custom Russian or English spellchecker.
Is it possible to make spellchecker ignore tilde sign in this case?

Thanks

**Comment by slavad** [comment]
E.g. "test" is marked as ok, but "test~" is marked as misspelled

**Comment by sanssecours** [comment]
Hi slavad,

for me the spell-checking seems to work correctly even if there is a `~`. The words

- Lorem
- ~Lorem
- Lorem~
- ~Lorem~

are underlined regardless of the chosen spelling language. The words

- test
- ~test
- test~
- ~test~

on the other hand are considered correct. Other applications, that use the built in spell checker show the same behaviour. Here are two screenshots:

TextMate:
![textmate](https://cloud.githubusercontent.com/assets/691989/5834967/5618cf0e-a163-11e4-8263-eb7cf1b9bde1.png)
TextEdit:
![textedit](https://cloud.githubusercontent.com/assets/691989/5834975/66831372-a163-11e4-9393-20501ca7d6eb.png)

> Is it possible to make spellchecker ignore tilde sign in this case?

I don't think TextMate has any specific features that would allow us to exclude part of words from spell-checking. You mentioned that you use a custom spell-checker. Does that mean that you don't use the built in spell-checking software and instead use a tool from a third party such as “ORFO”? If that is the case, then I think the best way to fix your problem would be to contact the supplier of the software and ask them to consider removing tilde characters from spell-checking. 

Kind regards,
  René

**Comment by slavad** [comment]
Yes, I use ORFO. 
> If that is the case, then I think the best way to fix your problem would be to contact the supplier of the software and ask them to consider removing tilde characters from spell-checking.
Well, they suggested me to contact you (bundle  developer) :)

**Comment by slavad** [comment]
@sanssecours, I'm new to bundle development, so could you help me: how to add some word to the list of language statements (I don't know the exact term)? For example I can see that words starting with backslash are not spellchecked.

**Comment by slavad** [comment]
forget it. I found a workaround for this: I made this definition ``\let\nb=~`` and replaced all tildas with it

**Comment by sanssecours** [comment]
> Well, they suggested me to contact you (bundle developer) :)

Of course they did :). You might mention to them that the built in spell checker handles tilde signs just fine, and that there are multiple tools to write TeX code. If they fix it, every tool will benefit from it.

>  I'm new to bundle development, so could you help me: how to add some word to the list of language statements (I don't know the exact term)? For example I can see that words starting with backslash are not spellchecked.

For that you would need to update the latex grammar. You can access the grammar by opening the bundle editor <kbd>^⌥⌘B</kbd>. Select LaTeX→Language Grammars→Latex to edit the language grammar for LaTeX. I would highly recommend **not** adding words containing tilde signs there, since that basically means that you would tell TextMate that these words are special statement of the LaTeX language. Words with backslashes for example are considered to be of type `support.function.general.tex`.

**Comment by slavad** [comment]
thx
