### ISSUE TITLE
import problem in case sensitive filesystem

### ISSUE THREAD

**Issue by cherini** [textmate/latex.tmbundle#129]
There is a problem importing tex.py, because it is located in "lib/python" instead of "lib/Python", as indicated in configure.py, texdoc.py, textmate.py and texparser.py (all in bin/). As a workaround I've created a symbolic link, but it could be an annoying problem for someone else.

Thanks.

**Comment by sanssecours** [comment]
Hi Renato,

thank you for the very helpful bug report! I fixed the bug in commit 6dc0b1de. Since OS X uses a case-insensitive file system by default, this should not be a problem for most users. Otherwise the current tests would have failed on my system and I would have caught this error myself :(.

Thanks again,
  René
