### ISSUE TITLE
Not finding files in ~/Library/texmf/tex/latex

### ISSUE THREAD

**Issue by pfissure** [textmate/latex.tmbundle#153]
I am working with a single .tex file (i.e. not a project) which has an \include{macro-file} in the preamble.  The file macro-file.tex is in ~/Library/texmf/tex/latex and it includes a standard set of latex macros that I use for all of my documents.

The presence of this \include{} causes problems with ESC completion.  For example if I type \ref{} and inside the braces I do OPT-ESC I get a tooltip that says "Could not find any file named macro-file" and I am offered no list of completions.  

The problem is not fixed by putting a full path to the file in the \include{}, i.e. \include{~/Library/texmf/tex/latex/macro-file.tex}  On the other hand, if I have a copy of macro-file in the same directory as the file I am working on there is no problem (with just plain \include{macro-file}).  Indeed in this case the completion lists will include commands in macro-file that are not in the main file I am working on.

I have added the directory ~/Library/texmf/tex/latex to the TextMate PATH, so that is also not the issue.

**Comment by sanssecours** [comment]
Hi pfissure,

thank you for the detailed bug report. The issue should be fixed in commit 30c428ec. If the problem still persist after the bundle was updated, please comment below.

> I have added the directory ~/Library/texmf/tex/latex to the TextMate PATH, so that is also not the issue.

If you mean the value `PATH` here, then I would recommend that you remove the directory `~/Library/texmf/tex/latex`. The more or less sole purpose of the [PATH variable](https://en.wikipedia.org/wiki/PATH_(variable)) is to specify the search path for (shell) programs such as `cd`. The value of `PATH` does not influence the completion commands of the LaTeX bundle.

Kind regards,
  René
