### ISSUE TITLE
Buttons at bottom of compile window no longer working

### ISSUE THREAD

**Issue by ciandorr** [textmate/latex.tmbundle#155]
At some point in the last few months, the buttons ('Re-run Latex', 'Create Bibliography', 'View in Skim' etc.) that appear in the bottom of the compile window stopped functioning.  I'm not sure if this problem is with the Latex mode or with TextMate.

**Comment by sanssecours** [comment]
Hi ciandorr,

thank you for the bug report. I can reproduce the issue in **TextMate 2.0-beta.12.24** on macOS 10.12 using the steps below.

# Steps to Reproduce

1. Create a new document

  ```tex
  \documentclass{article}
  \begin{document}
  :)
  \end{document}
  ```

2. Save the document as `Test.tex`
3. Run “Typeset & View (PDF)” (<kbd>⌘</kbd> + <kbd>R</kbd>)
4. Press the button ”Clean“ in the HTML outptut

# Expected Result

The HTML output shows the following output:

```
Removed Test.aux

Removed Test.fdb_latexmk

Removed Test.fls

Removed Test.log

Removed Test.synctex.gz
```

# Actual Result

Nothing happens.

# Notes

- The above steps work fine in the latest regular release of TextMate (**2.0-beta.12.4**) 
- The button “Preferences” still works in TextMate 2.0-beta.12.24
- The code responsible for the functionality of the buttons is located in [texlib.js](https://github.com/textmate/latex.tmbundle/blob/master/Support/lib/JavaScript/texlib.js#L39-L46) and uses `TextMate.system`. Since the button “Preferences” still works in newer versions of TextMate I suspect the problem has something to do with the `onreadoutput` property.

@sorbits Allan, could you please take a look at this issue. Thank you!

**Comment by sorbits** [comment]
Just a FYI the nightly build that was just released does not include the commit that fixes this issue, this was not intentional, sorry about that.

Next build **will** include the fix!
