### ISSUE TITLE
Warning window appearing then disappearing

### ISSUE THREAD

**Issue by ataiya** [textmate/latex.tmbundle#160]
I am using **watch document**. The warning window appears (mentioning to look at the latexmk log file) then automatically disappears. There are no errors in the log file... making it quite annoying to resolve as you might image.

Any suggestion?

**Comment by sanssecours** [comment]
I guess the issue here is a transient error reported by Latexmk. I would try the following:

1. Disable “Watch Document“.
2. Run the command “Clean“ to remove auxiliary files.
2. Run “Typeset & View (PDF)“. Make sure that you checked “Use Latexmk“ inside the bundle preferences.
3. Take a look at the HTML output. Theoretically it should display the problematic error message.
4. Fix the problem reported in the HTML output.
5. Run “Watch Document“.

The real fix for your problem would probably be a version of `texparser`, that stores and reports old error message, even if the contain no line information. Hopefully I have time to fix this problem somewhere in the future.

**Comment by ataiya** [comment]
Thanks for the suggestion, I found the problem. Do you guys think we can have a link embedded in the error popup whenever "look at the latexmk log file" appears?

**Comment by sanssecours** [comment]
> Do you guys think we can have a link embedded in the error popup whenever "look at the latexmk log file" appears?

As far as I know, the answer to this question is currently no. The simple notification window only allows us to display text. I assume we can display a link, if we create a custom nib for the notification window. This is certainly something worth considering, since we can then improve the output of the other error messages too.
