### ISSUE TITLE
Text links broken when using \input{...}

### ISSUE THREAD

**Issue by ataiya** [textmate/latex.tmbundle#174]
I store figures in my papers in their own tex file. My master find include the sub-tex files, with at most a depth 2 of dependencies. When I command+shift+click, I am often sent to the figure latex file rather than to the correct location. Known problem? Solutions?

Using this document class:
`` \documentclass[acmtog, review]{acmart}``

**Comment by sanssecours** [comment]
Thank you for the bug report, Andrea. Can you please provide [steps to reproduce the problem](https://github.com/textmate/textmate/wiki/Writing-Bug-Reports)?

**Comment by ataiya** [comment]
I am afraid I cannot share the document on which I can easily reproduce the problem right now.
I have tested on [a blank template](https://github.com/ataiya/latex_siggraph_template), and there it doesn't occur.

**Comment by sanssecours** [comment]
> I am afraid I cannot share the document on which I can easily reproduce the problem right now.

You can replace the original text and figures of the document with placeholders. This way you do not have to share any confidential data. It also makes sense to just remove parts of the document, as long as you can reproduce the initial issue. A minimal example is  much more interesting, than a document containing a lot of code, anyway.

**Comment by ataiya** [comment]
Alright, I'll try to see what I can do.

**Comment by sanssecours** [comment]
Thank you for providing the example. On my machine – using Skim 1.4.32 – <kbd>⇧</kbd>+<kbd>⌘</kbd>+clicking somewhere within Section 1.1 opens `main.tex`. That is not the desired behavior either, but differs slightly from the situation you described. 

Anyway, opening the appropriate file at the correct line is actually Skim’s task in this scenario. As you can see in `Skim`→`Preferences…`→`Sync`:

<img width="607" alt="sync" src="https://user-images.githubusercontent.com/691989/35643502-cdde4b6a-06c6-11e8-89d4-7a1e511bea6a.png">

Skim just calls `mate` (the command line wrapper for TextMate) specifying the appropriate file and line number. Since Skim specifies the file (`main.tex`), TextMate (or any other editor for that matter) will just open this file. I opened a bug report in [Skim’s bug tracker](https://sourceforge.net/p/skim-app/bugs/1231) describing the issue.
